# Helm charts list, one per line, supports # comments and blank lines
# Short form -> pulled from docker.io by default, e.g. bitnamicharts/redis:27.0.13
# Full form  -> any OCI registry, e.g. oci://ghcr.io/some-org/some-chart:1.2.3

#bitnamicharts/redis:27.0.13
#bitnamicharts/valkey:6.1.14
#bitnamicharts/postgresql:18.7.11
#bitnamicharts/nginx:25.0.12
#bitnamicharts/rabbitmq:16.0.14
#bitnamicharts/grafana:12.1.8
#bitnamicharts/grafana-alloy:1.0.7
#bitnamicharts/grafana-loki:6.0.6
#bitnamicharts/victoriametrics:0.1.31
#bitnamicharts/prometheus:2.1.23
#bitnamicharts/mysql:14.0.3
bitnamicharts/minio:17.0.21
bitnamicharts/redis-cluster:13.0.4
bitnamicharts/valkey-cluster:3.0.24
bitnamicharts/postgresql-ha:16.3.2
